### ISSUE TITLE
2.1.45alpha error - needs updating probably

### ISSUE THREAD

**Issue by AnKingMed** [BlueGreenMagick/Image-Editor#12]
2.1.45 alpha changed a bunch of the editor and that's likely to stay. Here's the error I got:

> > Image Editor Error: Unmatching image src
> 
> Please report the issue in this addon's github https:github.com/bluegreenmagick/image-editor
> 
> Src1: None
> Src2: http://127.0.0.1:56762/paste-5f2b27f35d9467e0b31b4559edecf5aefa9b81d1.jpg
> Note field content: <img src="paste-5f2b27f35d9467e0b31b4559edecf5aefa9b81d1.jpg" class="resizer">

**Comment by BlueGreenMagick** [comment]
Found a way to fix it without rewriting! :)
