### ISSUE TITLE
Unmatching image src error

### ISSUE THREAD

**Issue by HR-Hckboi** [BlueGreenMagick/Image-Editor#13]
Im not sure why, but when I uploaded a picture to anki and tried editing it, it gives an error message:

**Image Editor Error: Unmatching image src

Please report the issue in this addon's github https:github.com/bluegreenmagick/image-editor

Src1: http://127.0.0.1:52832/prokaryote%20cell.png
Src2: http://127.0.0.1:52832/prokaryote cell.png
Note field content: <div><img src="prokaryote cell.png"><br></div>Name <b>all </b>subcellular structures**

**Comment by BlueGreenMagick** [comment]
This issue (#3) was fixed in the latest version! If you are using Anki v2.1.41+, please update the addon.
