### ISSUE TITLE
Editing is not saved

### ISSUE THREAD

**Issue by ankidoc** [BlueGreenMagick/Image-Editor#19]
hey there! I'm using anki 2.1.45 and when I edit the image and click save it is not saving the changes!

Please help!

![CleanShot 2021-12-20AddAnki at 11 40 53](https://user-images.githubusercontent.com/81517565/146754648-7d316240-1eb5-496a-bff4-110e87066d6f.gif)

it's updated to the latest version for this add on

here is a list of add ons (maybe some interference?

![CleanShot 2021-12-20CleanShotCleanShot at 12 10 01](https://user-images.githubusercontent.com/81517565/146758357-8f2eaf25-9209-431e-b85b-6828f70ced2b.png)

**Comment by BlueGreenMagick** [comment]
I've tested on 2.1.45, and I'm unable to reproduce the error. Does the error happen all the time, or once in a while?

**Comment by ankidoc** [comment]
thanks for answering! yes it occurs permanently. And with every note type.

**Comment by BlueGreenMagick** [comment]
Can you share the HTML code of the field? You can do that by pressing `Ctrl + Shift + X` in the editor(or add cards window) while editing the field that has the image.

**Comment by ankidoc** [comment]
sure!
hope that helps!

![CleanShot 2021-12-21CleanShotCleanShot at 11 33 41](https://user-images.githubusercontent.com/81517565/146916022-00199c2b-0bdc-4ff3-a38d-6c0170e4fd91.png)
![CleanShot 2021-12-21CleanShotCleanShot at 11 35 53](https://user-images.githubusercontent.com/81517565/146916044-dab7f8d3-fbd4-4238-867f-4961675ca157.png)
![CleanShot 2021-12-21CleanShotCleanShot at 11 36 02](https://user-images.githubusercontent.com/81517565/146916051-498b873a-ff88-42a6-85c8-357510854886.png)
![CleanShot 2021-12-21CleanShotCleanShot at 11 36 55](https://user-images.githubusercontent.com/81517565/146916078-bde07d64-6082-44b6-8994-c5fc72b56449.png)

**Comment by BlueGreenMagick** [comment]
Yeah, looks like the addon doesn't work with Tippy Tooltips addon. I can't even get the image editor window open. Strange that only saving doesn't work for you.

The problem is that Image Editor's js script runs after the Tippy Tooltips js script. Tippy Tooltip's script causes an error, resulting in the rest of the script (including Image Editor's) not running.

Does it work fine with Tippy Tooltip disabled?

**Comment by ankidoc** [comment]
Yeah disabled works fine! Is there a change I can change the loading behavior in 2.1.45 without upgrading to 2.1.49?

**Comment by BlueGreenMagick** [comment]
You can edit Tippy Tooltip's code `editor.py` line 17 to
```python
    return js + "try { TippyTooltips.initNote(" + json.dumps(args) + "); } catch { };"
```

and it should work
