### ISSUE TITLE
Regarding the error in Korean

### ISSUE THREAD

**Issue by tedddy1251** [BlueGreenMagick/Image-Editor#20]
Dear the creator of the Image Editor,
Thank you for your reply!

I've checked
①my current Anki version is ⁨2.1.49 and
②updated to the newest version
but still the issue lasts.

Sorry that I don't know what you mean by SCV and view > source direction,
but I tried to collect as many info as possible.
Below is the error message and how I got it
by typing 안녕하세요! (Hello!) 

hope this helps.

Thanks for your help :)
----------------------------------------------------
Caught exception:
Traceback (most recent call last):
File "aqt\webview.py", line 41, in cmd
File "aqt\webview.py", line 142, in _onCmd
File "aqt\webview.py", line 595, in _onBridgeCmd
File "C:\Users\Ted\AppData\Roaming\Anki2\addons21\307397307\annotation.py", line 131, in on_bridge_cmd
self.load_img()
File "C:\Users\Ted\AppData\Roaming\Anki2\addons21\307397307\annotation.py", line 160, in load_img
img_data = json.dumps(img_path.read_text())
File "pathlib.py", line 1236, in read_text
UnicodeDecodeError: 'cp949' codec can't decode byte 0xec in position 484: illegal multibyte sequence
----------------------------------------------------

![image](https://user-images.githubusercontent.com/105297162/167649058-71217c2e-fc32-461f-9194-eca4b749dd79.png)
![image](https://user-images.githubusercontent.com/105297162/167649140-b112d5a6-1755-45cb-8b4a-b13f40f98d4e.png)
![image](https://user-images.githubusercontent.com/105297162/167649160-dff7cf80-8479-4901-b284-37284dd3f952.png)
![image](https://user-images.githubusercontent.com/105297162/167649215-d25eb8ec-09bc-4e0f-a5e3-5bdb3183fa69.png)

**Comment by BlueGreenMagick** [comment]
Thanks for the _very_ detailed bug report! I think I figured out what is going wrong. (Windows open a file in cp949 by default, while macs uses utf-8) 

It should be fixed in the latest update

**Comment by tedddy1251** [comment]
Dear my lifesaver, 
It works perfectly on not only Korean, but Japanese and Chinese as well.
You literally upgraded my Anki to another level.

Now, I'm thinking of using it as editable mindmap
You are the best!

![이미지 014](https://user-images.githubusercontent.com/105297162/167761279-d2490efe-af46-4e36-929c-9226f412bfe4.jpg)
.
