### ISSUE TITLE
2.1.53 qt6 bug deletes adjacent image

### ISSUE THREAD

**Issue by jcznk** [BlueGreenMagick/Image-Editor#21]
Version ⁨2.1.53 (f6ecddef)⁩
Python 3.9.7 Qt 6.3.0 PyQt 6.3.0
Windows 10

If a field contains 2+ images and I use the addon to edit one of them, after clicking on 'Save' the following occurs:
- the image does not get edited
- but: the very next image is replaced by the edited version of the first one.

So one image gets duplicated (1 unedited + 1 edited) and another gets lost.
This happens even if there are line breaks or even text to separate them.
No problem occurs if the field contains only 1 image or if I edit the last (rightmost/most bottom) one.

E.g. 
![image](https://user-images.githubusercontent.com/60730312/169883812-96d053d2-1195-4e1d-a66b-ea593ff7ea56.png)
![image](https://user-images.githubusercontent.com/60730312/169883825-ff68e18f-64bf-4c00-b880-d9d620a58e9d.png)
![image](https://user-images.githubusercontent.com/60730312/169883836-4b7b9057-6d0a-4e8f-bc2b-ff68e8101c3c.png)

**Comment by BlueGreenMagick** [comment]
Thanks for the detailed report! It should be fixed now.

**Comment by jcznk** [comment]
Hello! Thank you for the quick response.

Sorry to be here again: unfortunately the addon is now giving a different problem.
The image being edited is now very large (it does not fit the screen) and if I try to change the zoom ratio the addon most often friezes
