### ISSUE TITLE
2.1.54Qt5 bug - not working

### ISSUE THREAD

**Issue by AnKingMed** [BlueGreenMagick/Image-Editor#23]
> Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.14.1 PyQt 5.14.1
> Platform: Mac 12.5.1
> Flags: frz=True ao=True sv=3
> Add-ons, last update check: 2022-09-03 10:02:30
> Add-ons possibly involved: ⁨Image Editor⁩
> 
> Caught exception:
> Traceback (most recent call last):
>   File "aqt.webview", line 568, in handler
>   File "aqt.editor", line 561, in <lambda>
>   File "/Users/Nick/Library/Application Support/Anki2/addons21/307397307/annotation.py", line 218, in <lambda>
>     n=new_name: s.replace_all_img_src(i, n))
>   File "/Users/Nick/Library/Application Support/Anki2/addons21/307397307/annotation.py", line 254, in replace_all_img_src
>     cnt = self._replace_all_img_src(orig_name, new_name)
>   File "/Users/Nick/Library/Application Support/Anki2/addons21/307397307/annotation.py", line 291, in _replace_all_img_src
>     res = mw.col.find_and_replace(
>   File "anki.collection", line 688, in find_and_replace
>   File "anki._backend.generated", line 1510, in find_and_replace
>   File "anki._backend", line 146, in _run_command
> anki.errors.InvalidInput: <pre>regex parse error:
>     (?i)(?P<first><img[^>]* src=)(?:"Dermatopathology\ \(2018\)\ 0025\-00\.jpg")|(?:'Dermatopathology\ \(2018\)\ 0025\-00\.jpg')(?P<second>[^>]*>)
>                                                      ^^
> error: unrecognized escape sequence</pre>

**Comment by BlueGreenMagick** [comment]
Fixed!
