### ISSUE TITLE
Image editor not working

### ISSUE THREAD

**Issue by Rmsz12** [BlueGreenMagick/Image-Editor#3]
When I try to use the image editor option on anki for the images that I have added on some cards I face this problem ( I have attached an image showing the error that I get ). On the other hand, when I use the image editor option for images already existing on the pre-made decks (images not added by me) it works as it supposed to. I would really appreciate any help and thank you so much!

Ps: whether I deleted the original image that I already attached or not, I still face the exact same problem!
![Screenshot 2020-12-22 174004](https://user-images.githubusercontent.com/76501747/102945936-d654e280-44c7-11eb-964b-194c3a2072ca.png)

**Comment by BlueGreenMagick** [comment]
Looks like an issue with whitespace - it gets converted to `%20` somewhere in the code. I'll come back to it sometime later.

**Comment by Rmsz12** [comment]
> Looks like an issue with whitespace - it gets converted to `%20` somewhere in the code. I'll come back to it sometime later.

Thats true, when I use images with no spaces in their names I wouldn't face any problem. Thanks a lot for this amazing add-on, my favourite part about it is that pictures are still editable and could be modified even after saving the images. God bless you for this add on dude, much love!

**Comment by BlueGreenMagick** [comment]
Since this still is an issue, I'll reopen it so I remember to fix this later.

**Comment by BlueGreenMagick** [comment]
Fixed!
