### ISSUE TITLE
Issues with "Resize images in editor"

### ISSUE THREAD

**Issue by mytestingsolution** [BlueGreenMagick/Image-Editor#5]
Your add-on is one of my absolute favorites! So useful...I also use "Resize images in editor" which allows drag and drop resizing of images in the editor and unfortunately, the two add-ons are not compatible.

Do you have any insights re what might be going on. I reached out to the author of that add-on but he/she said they didn't have time to figure it out currently. 

Resize images in editor - https://ankiweb.net/shared/info/1103084694

Regardless, thank you so much for your contribution to the Anki community!

**Comment by BlueGreenMagick** [comment]
Can I ask in what sense they aren't compatible? Does it produce an error?

**Comment by mytestingsolution** [comment]
Hi! Thank you for your reply and sorry for not including more details. When
I open the image editor, there is no image, just blank: The resizer
prevents right-clicking on images, but I'm opening the image editor via the
toolbar icon. Does that make sense?

[image: image.png]
*Were we helpful? Do you like our practice tests? Leave a review on
Amazon.com!*
<https://www.amazon.com/Testing-Solutions-Critical-Analysis-Reasoning-ebook/dp/B00CIGXJYI/ref=sr_1_1?s=digital-text&ie=UTF8&qid=1472414547&sr=1-1#customerReviews>

*Testing Solutions, LLC - The Key to Unlocking Your Future*

**Comment by BlueGreenMagick** [comment]
The toolbar icon is for drawing new images. Editing images can only be done by right clicking.
