### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by alaskakw** [BlueGreenMagick/Image-Editor#7]
Error message when attempting to edit photo:

Image Editor Error: Unmatching image src

Please report the issue in this addon's github https:github.com/bluegreenmagick/image-editor

Src1: None
Src2: http://127.0.0.1:58140/paste-3676492005880.jpg
Note field content: <div><i>thrombocytopenia is a contraindication to expectant management&nbsp;</i><i>in addition to&nbsp;refractory&nbsp;<b>hypertension</b>,&nbsp;<b>non-reassuring</b>&nbsp;fetal surveillance, 2x normal&nbsp;<b>LFTs</b>,&nbsp;<b>eclampsia</b>,&nbsp;<b>CNS</b>&nbsp;sx,&nbsp;<b>oliguria</b></i></div><div><img src="Timingdeliverreeclampsia.gif" style="width: 554px;"><i><b><br></b></i></div><div><i><b><br></b></i></div><div><i></i><i><img src="i found chart!.png" style="width: 853px;"></i></div><div><i><br></i></div><div><i><br></i></div><img src="paste-3676492005880.jpg" style="width: 853px;">

**Comment by BlueGreenMagick** [comment]
The last 3 issues looks like the same one, so I'll combine all into #9.
