### ISSUE TITLE
error for all images, running 2.1.38

### ISSUE THREAD

**Issue by jman004** [BlueGreenMagick/Image-Editor#8]
mage Editor Error: Unmatching image src

Please report the issue in this addon's github https:github.com/bluegreenmagick/image-editor

Src1: None
Src2: paste-35b4e786512e352a7eaaea304c49b88f50f66714.png
Note field content:<div><img src="paste-35b4e786512e352a7eaaea304c49b88f50f66714.png" class="" style="height: 429px; width: 329px;"><br></div>

**Comment by BlueGreenMagick** [comment]
The last 3 issues looks like the same one, so I'll combine all into #9.
